eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://103.177.252.16:8761/eureka/
 instance:
  prefer-ip-address: true
  
services:
 payment:
  endpoints:
   endpoint:
    uri: http://PAYMENT-SERVICE/payment/dopayment
 order:
  endpoints:
   endpoint:
    uri: http://ORDER-SERVICE/order/saveorder
    
